# Generated by Django 2.2.1 on 2019-05-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=500)),
                ('item_price', models.FloatField()),
                ('item_count', models.IntegerField()),
                ('vendor', models.CharField(max_length=50)),
                ('vendor_address', models.CharField(max_length=500)),
            ],
        ),
    ]
