# Generated by Django 2.2.1 on 2019-05-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploaddata',
            name='item',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fileuploaddata',
            name='item_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fileuploaddata',
            name='item_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fileuploaddata',
            name='item_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fileuploaddata',
            name='vendor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fileuploaddata',
            name='vendor_address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
